### ISSUE TITLE
failed on pacbio simulation data

### ISSUE THREAD

**Issue by qinqian** [ekimb/mapquik#12]
Dear developer,

Thank you for developing the fastest aligner! I am exploring it in human PacBio simulation data with hg38 reference after installing mapquik following your tutorial, but it failed with the following errors, is there a way to fix this problem? Thanks!

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 27 but the index is 27', /home/ubuntu/.cargo/git/checkouts/rust-seq2kminmers-a8719f5d5deb1022/2d4d541/src/nthash_hpc_simd.rs:62:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

Best,
Qian

**Comment by rchikhi** [comment]
Hi! Thanks for reporting this. Would it be feasible for you to upload us the reads where this problem occurs?

**Comment by qinqian** [comment]
Yes, please see the reads that this problem occurs in the attachment (https://ndownloader.figshare.com/files/27676470, please see the Pac_fus_sim_75err.fastq.gz data). Also here is the full command and logs:

``` {bash}
~/mapquik/target/release/mapquik --reference ./LR-fusion-benchmarking/20230711_030513_ctat_LR_fusion_wf/call-CTAT_LR_FUSION_TASK/work/ctat_genome_lib_build_dir/ref_genome.fa ./LR-fusion-tools/StarLong/LongReadFusionSimulation/Pac_fus_sim_75err.fastq.gz
Reference file: ./LR-fusion-benchmarking/20230711_030513_ctat_LR_fusion_wf/call-CTAT_LR_FUSION_TASK/work/ctat_genome_lib_build_dir/ref_genome.fa
Format: FASTA
Warning: Using default k value (5).
Warning: Using default l value (31).
Warning: Using default buffer size (1X).
Warning: Using default queue length (200).
Warning: Using default density value (1%).
Warning: Using default number of threads (8).
Warning: Using default minimum chain length (4).
Warning: Using default minimum number of matching seeds (11).
Warning: Using default maximum seed gap difference (2000).
Warning: Using default output prefix (mapquik-k5-d0.01-l31).
Using HPC ntHash, with SIMD
Indexed reference chr1: 3928825 k-min-mers.
Indexed reference chr2: 3500163 k-min-mers.
Indexed reference chr3: 2848119 k-min-mers.
Indexed reference chr4: 2733285 k-min-mers.
Indexed reference chr5: 2610152 k-min-mers.
Indexed reference chr6: 2463178 k-min-mers.
Indexed reference chr7: 2290837 k-min-mers.
Indexed reference chr8: 2092868 k-min-mers.
Indexed reference chr9: 2302778 k-min-mers.

Indexed reference chr10: 1931966 k-min-mers.
Indexed reference chr11: 1951245 k-min-mers.
Indexed reference chr12: 1919222 k-min-mers.
Indexed reference chr14: 1846800 k-min-mers.
Indexed reference chr13: 1950202 k-min-mers.
Indexed reference chr15: 1795526 k-min-mers.
Indexed reference chr16: 1464829 k-min-mers.
Indexed reference chr17: 1202929 k-min-mers.
Indexed reference chr19: 846299 k-min-mers.
Indexed reference chr18: 1161274 k-min-mers.
Indexed reference chr20: 938788 k-min-mers.
Indexed reference chr21: 793937 k-min-mers.
Indexed reference chr22: 952360 k-min-mers.
Indexed reference chrX: 2260056 k-min-mers.
Indexed reference chrY: 1407308 k-min-mers.
Indexed reference chrM: 215 k-min-mers.
Indexed reference GL000008.2: 3066 k-min-mers.
Indexed reference GL000009.2: 2935 k-min-mers.
Indexed reference GL000194.1: 2743 k-min-mers.
Indexed reference GL000195.1: 2673 k-min-mers.
Indexed reference GL000205.2: 2755 k-min-mers.
Indexed reference GL000208.1: 1400 k-min-mers.
Indexed reference GL000213.1: 2339 k-min-mers.
Indexed reference GL000214.1: 2010 k-min-mers.
Indexed reference GL000216.2: 2528 k-min-mers.
Indexed reference GL000218.1: 2398 k-min-mers.
Indexed reference GL000219.1: 2578 k-min-mers.
Indexed reference GL000220.1: 2230 k-min-mers.
Indexed reference GL000221.1: 2106 k-min-mers.
Indexed reference GL000224.1: 2707 k-min-mers.
Indexed reference GL000225.1: 3158 k-min-mers.
Indexed reference GL000226.1: 190 k-min-mers.
Indexed reference KI270302.1: 25 k-min-mers.
Indexed reference KI270303.1: 22 k-min-mers.
Indexed reference KI270304.1: 32 k-min-mers.
Indexed reference KI270305.1: 17 k-min-mers.
Indexed reference KI270310.1: 10 k-min-mers.
Indexed reference KI270311.1: 317 k-min-mers.
Indexed reference KI270312.1: 15 k-min-mers.
Indexed reference KI270315.1: 32 k-min-mers.
Indexed reference KI270316.1: 17 k-min-mers.
Indexed reference KI270317.1: 1151 k-min-mers.
Indexed reference KI270320.1: 63 k-min-mers.
Indexed reference KI270322.1: 535 k-min-mers.
Indexed reference KI270329.1: 3 k-min-mers.
Indexed reference KI270330.1: 18 k-min-mers.
Indexed reference KI270333.1: 34 k-min-mers.
Indexed reference KI270334.1: 17 k-min-mers.
Indexed reference KI270335.1: 16 k-min-mers.
Indexed reference KI270336.1: 16 k-min-mers.
Indexed reference KI270337.1: 7 k-min-mers.
Indexed reference KI270338.1: 24 k-min-mers.
Indexed reference KI270340.1: 21 k-min-mers.
Indexed reference KI270362.1: 38 k-min-mers.
Indexed reference KI270363.1: 19 k-min-mers.
Indexed reference KI270364.1: 42 k-min-mers.
Indexed reference KI270366.1: 134 k-min-mers.
Indexed reference KI270371.1: 42 k-min-mers.
Indexed reference KI270372.1: 18 k-min-mers.
Indexed reference KI270373.1: 12 k-min-mers.
Indexed reference KI270374.1: 23 k-min-mers.
Indexed reference KI270375.1: 38 k-min-mers.
Indexed reference KI270376.1: 12 k-min-mers.
Indexed reference KI270378.1: 8 k-min-mers.
Indexed reference KI270379.1: 10 k-min-mers.
Indexed reference KI270381.1: 21 k-min-mers.
Indexed reference KI270382.1: 60 k-min-mers.
Indexed reference KI270383.1: 24 k-min-mers.
Indexed reference KI270384.1: 19 k-min-mers.
Indexed reference KI270385.1: 8 k-min-mers.
Indexed reference KI270386.1: 32 k-min-mers.
Indexed reference KI270387.1: 16 k-min-mers.
Indexed reference KI270388.1: 16 k-min-mers.
Indexed reference KI270389.1: 8 k-min-mers.
Indexed reference KI270390.1: 27 k-min-mers.
Indexed reference KI270391.1: 13 k-min-mers.
Indexed reference KI270392.1: 9 k-min-mers.
Indexed reference KI270393.1: 19 k-min-mers.
Indexed reference KI270394.1: 15 k-min-mers.
Indexed reference KI270395.1: 8 k-min-mers.
Indexed reference KI270396.1: 12 k-min-mers.
Indexed reference KI270411.1: 31 k-min-mers.
Indexed reference KI270412.1: 14 k-min-mers.
Indexed reference KI270414.1: 29 k-min-mers.
Indexed reference KI270417.1: 30 k-min-mers.
Indexed reference KI270418.1: 27 k-min-mers.
Indexed reference KI270419.1: 12 k-min-mers.
Indexed reference KI270420.1: 31 k-min-mers.
Indexed reference KI270422.1: 10 k-min-mers.
Indexed reference KI270423.1: 10 k-min-mers.
Indexed reference KI270424.1: 29 k-min-mers.
Indexed reference KI270425.1: 16 k-min-mers.
Indexed reference KI270429.1: 15 k-min-mers.
Indexed reference KI270435.1: 1304 k-min-mers.
Indexed reference KI270438.1: 1962 k-min-mers.
Indexed reference KI270442.1: 5901 k-min-mers.
Indexed reference KI270448.1: 88 k-min-mers.
Indexed reference KI270465.1: 16 k-min-mers.
Indexed reference KI270466.1: 22 k-min-mers.
Indexed reference KI270467.1: 48 k-min-mers.
Indexed reference KI270468.1: 51 k-min-mers.
Indexed reference KI270507.1: 76 k-min-mers.
Indexed reference KI270508.1: 24 k-min-mers.
Indexed reference KI270509.1: 27 k-min-mers.
Indexed reference KI270510.1: 30 k-min-mers.
Indexed reference KI270511.1: 131 k-min-mers.
Indexed reference KI270512.1: 327 k-min-mers.
Indexed reference KI270515.1: 102 k-min-mers.
Indexed reference KI270516.1: 17 k-min-mers.
Indexed reference KI270517.1: 49 k-min-mers.
Indexed reference KI270518.1: 36 k-min-mers.
Indexed reference KI270519.1: 2023 k-min-mers.
Indexed reference KI270521.1: 96 k-min-mers.
Indexed reference KI270522.1: 74 k-min-mers.
Indexed reference KI270528.1: 40 k-min-mers.
Indexed reference KI270529.1: 20 k-min-mers.
Indexed reference KI270530.1: 31 k-min-mers.
Indexed reference KI270538.1: 1648 k-min-mers.
Indexed reference KI270539.1: 1 k-min-mers.
Indexed reference KI270544.1: 17 k-min-mers.
Indexed reference KI270548.1: 18 k-min-mers.
Indexed reference KI270579.1: 467 k-min-mers.
Indexed reference KI270580.1: 22 k-min-mers.
Indexed reference KI270581.1: 85 k-min-mers.
Indexed reference KI270582.1: 89 k-min-mers.
Indexed reference KI270583.1: 12 k-min-mers.
Indexed reference KI270584.1: 53 k-min-mers.
Indexed reference KI270587.1: 32 k-min-mers.
Indexed reference KI270588.1: 83 k-min-mers.
Indexed reference KI270589.1: 713 k-min-mers.
Indexed reference KI270590.1: 72 k-min-mers.
Indexed reference KI270591.1: 87 k-min-mers.
Indexed reference KI270593.1: 33 k-min-mers.
Indexed reference KI270706.1: 2603 k-min-mers.
Indexed reference KI270707.1: 464 k-min-mers.
Indexed reference KI270708.1: 1902 k-min-mers.
Indexed reference KI270709.1: 942 k-min-mers.
Indexed reference KI270710.1: 615 k-min-mers.
Indexed reference KI270711.1: 638 k-min-mers.
Indexed reference KI270712.1: 2448 k-min-mers.
Indexed reference KI270713.1: 597 k-min-mers.
Indexed reference KI270714.1: 614 k-min-mers.
Indexed reference KI270715.1: 2067 k-min-mers.
Indexed reference KI270716.1: 2015 k-min-mers.
Indexed reference KI270717.1: 593 k-min-mers.
Indexed reference KI270718.1: 553 k-min-mers.
Indexed reference KI270719.1: 2517 k-min-mers.
Indexed reference KI270720.1: 557 k-min-mers.
Indexed reference KI270721.1: 1480 k-min-mers.
Indexed reference KI270722.1: 2815 k-min-mers.
Indexed reference KI270723.1: 536 k-min-mers.
Indexed reference KI270724.1: 588 k-min-mers.
Indexed reference KI270725.1: 2438 k-min-mers.
Indexed reference KI270726.1: 635 k-min-mers.
Indexed reference KI270727.1: 6458 k-min-mers.
Indexed reference KI270728.1: 32320 k-min-mers.
Indexed reference KI270729.1: 4122 k-min-mers.
Indexed reference KI270730.1: 1629 k-min-mers.
Indexed reference KI270731.1: 2177 k-min-mers.
Indexed reference KI270732.1: 569 k-min-mers.
Indexed reference KI270733.1: 2665 k-min-mers.
Indexed reference KI270734.1: 2462 k-min-mers.
Indexed reference KI270735.1: 623 k-min-mers.
Indexed reference KI270736.1: 2710 k-min-mers.
Indexed reference KI270737.1: 1533 k-min-mers.
Indexed reference KI270738.1: 1510 k-min-mers.
Indexed reference KI270739.1: 1057 k-min-mers.
Indexed reference KI270740.1: 548 k-min-mers.
Indexed reference KI270741.1: 2339 k-min-mers.
Indexed reference KI270742.1: 2705 k-min-mers.
Indexed reference KI270743.1: 3066 k-min-mers.
Indexed reference KI270744.1: 2443 k-min-mers.
Indexed reference KI270745.1: 622 k-min-mers.
Indexed reference KI270746.1: 913 k-min-mers.
Indexed reference KI270747.1: 2857 k-min-mers.
Indexed reference KI270748.1: 1395 k-min-mers.
Indexed reference KI270749.1: 2264 k-min-mers.
Indexed reference KI270750.1: 2124 k-min-mers.
Indexed reference KI270751.1: 2083 k-min-mers.
Indexed reference KI270752.1: 397 k-min-mers.
Indexed reference KI270753.1: 946 k-min-mers.
Indexed reference KI270754.1: 574 k-min-mers.
Indexed reference KI270755.1: 534 k-min-mers.
Indexed reference KI270756.1: 1084 k-min-mers.
Indexed reference KI270757.1: 1128 k-min-mers.
Indexed 41704452 unique k-min-mers in 52.499987917s.
thread '<unnamed>' panicked at 'index out of bounds: the len is 22 but the index is 22', /home/ubuntu/.cargo/git/checkouts/rust-seq2kminmers-a8719f5d5deb1022/2d4d541/src/nthash_hpc_simd.rs:62:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by rchikhi** [comment]
Excellent, thanks for providing the reads! looking into it

**Comment by rchikhi** [comment]
The culprit was a short read that, once HPC'd, was smaller than the minimizer length

**Comment by rchikhi** [comment]
also btw those reads contain lowercase characters, which aren't supported by mapquik yet..

**Comment by qinqian** [comment]
I tested the updated mapquik on my side, it is working now! The only note is to update the cargo packages using:

```bash
cargo clean 
cargo update
cargo +nightly build --release
~/mapquik/target/release/mapquik --reference ./LR-fusion-benchmarking/20230711_030513_ctat_LR_fusion_wf/call-CTAT_LR_FUSION_TASK/work/ctat_genome_lib_build_dir/ref_genome.fa ./LR-fusion-tools/StarLong/LongReadFusionSimulation/Pac_fus_sim_75err.fastq.gz
```

I would suggest release binary executable of `mapquik` as well. Thanks!

**Comment by rchikhi** [comment]
Excellent! yes a binary is planned
